---
title: "QPot: An R Package for Stochastic Differential Equation Quasi-Potential Analysis"
author:
  - "Christopher Moore, Chris Stieha, Ben Nolting, Maria Cameron, and Karen Abbott"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{0. Intro to quasi-potential analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Introduction to QPot
========================================================

### What is QPot?
**QPot** is an abbreviation for an R package for **Q**uasi-**Pot**ential analysis, which is a technique used to determine relative probability and stability in 2-dimensional stochastic systems.

### How does QPot work?
The quasi-potential is calculated numerically for 2-dimensional stochastic equations through an ordered upwind method developed by Sethian and Vladimirsky,

> J. A. Sethian and A. Vladimirsky. Ordered upwind methods for static Hamilton-Jacobi equations. Proceedings of the National Academy of Sciences, 98(20):11069–11074, 2001.

> J. A. Sethian and A. Vladimirsky. Ordered upwind methods for static Hamilton-Jacobi equations: Theory and algorithms. SIAM Journal on Numerical Analysis, 41(1):325–363, 2003.

and expanded on by Cameron

> M. K. Cameron. Finding the quasipotential for nongradient SDEs. Physica D, 241(18):1532–1550, 2012.

Nolting and Abbott have recently introduced the method to the field of ecology

> B. C. Nolting and K. C. Abbott. Balls, cups, and quasi-potentials: Quantifying stability in stochastic systems. Ecology, 97(4):850–864, 2016.

and we have recently published a detailed paper on how to use **QPot**

> C. Moore, C. Stieha, B. Nolting, M. Cameron, and K. Abbott. QPot: Quasi-Potential Analysis for Stochastic Differential Equations, 2016. URL [https://www.R-project.org/package=QPot](https:// github.com/bmarkslash7/QPot). R package version 1.2.

This vignette is a condensed version of Moore et al. (2016), mostly focusing on Example 1.

### How can I get QPot?
**QPot** can be downloaded like any other package from CRAN:

```R
	install.packages(pkgs = "QPot")
```
or for the most recent working version from [GitHub](https://github.com/bmarkslash7/QPot):
```R
	devtools::install_github(repo = "bmarkslash7/QPot")
```
then simply load the library:
```R
	library(package = "QPot")
```

### Why all of the vignettes?
We break the vignettes into sections similar to the way we do in Moore et al. (2016).  They're broken into 6 natural steps:

	1. Analyzing the deterministic skeleton
	2. Stochastic simulation
	3. Local quasi-potential calculation
	4. Global quasi-potential calculation
	5. Global quasi-potential visualization
	6. Vector field decomposition

Analyzing the deterministic skeleton (1) goes through the process of taking a set of ordinary (non-stochastic) differential equations and examining its dynamics. (2) Adds stochasticity to (1), and we see that we need a tool to determine how the system will behave.  (3) Is the first part of quasi-potential analysis, where a local quasi-potential is calculated for each stable equilibrium.  (4) Combines each local quasi-potential  into a global quasi-potential surface.  (5) Visualized the global quasi-potential surface.  (6) Performs a vector field decomposition of the deterministic direction field, the gradient field, and remainder field.