---
title: "QPot: An R Package for Stochastic Differential Equation Quasi-Potential Analysis"
author:
  - "Christopher Moore, Chris Stieha, Ben Nolting, Maria Cameron, and Karen Abbott"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 1
vignette: >
  %\VignetteIndexEntry{2. Stochastic simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Stochastic simulation
========================================================
## Example 1 from Moore et al. (2016)
### Creating a model with stochasticity
In the previous vignette we used an example of a coupled consumer-resource equation developed for plankton and their consumers.  We now write the equation as a stochastic differential equation:

$$dX(t) = \left(\alpha X(t)\left(1 - \frac{X(t)}{\beta}\right) - \frac{\delta X^2(t)y(t)}{\kappa + X^2(t)}\right)dt + \sigma dW_1(t) \\
dY(t) = \left(\frac{\gamma X^2(t)Y(t)}{\kappa + X^2(t)} - \mu Y^2(t)\right) + \sigma dW_1(t)$$

There are several existing packages in R that will run stochastic simulations (see references in [CRAN Task View: Differential Equations](https://cran.r-project.org/web/views/DifferentialEquations.html)), but we include a less-computationally-efficient function for less-intensive simulations that are sufficient for our purposes and takes arguments in the form that we later use for the quasi-potential analysis.

### Running the simulation
Specifically, we created `TSTraj` (for **T**ime **S**eries **Traj**ectory), to take a equations as strings, with the option to specify the parameter values as a separate list.  `TSTraj` allows users to add stochasticity to the model (`sigma`), control  the timestep ($\delta t$), set upper and lower bounds (e.g., a lower bound of 0 may be useful for biologists studying populations since a population of < 0 is yet to be discovered), and returns a matrix with the numbers of rows equal to the total time steps ($\delta t \times T$) and two columns for each state variable (e.g., $X$ and $Y$).

Specifying the above equations can be separate from the parameters:
```R
var.eqn.x <- "(alpha * x) * (1 - (x / beta)) - ((delta * (x^2) * y) / (kappa + (x^2)))"
var.eqn.y <- "((gamma * (x^2) * y) / (kappa + (x^2))) - mu * (y^2)"
model.parms <- c(alpha = 1.54, beta = 10.14, delta = 1, gamma = 0.476, kappa = 1,
  mu = 0.112509)
```
or together, using `QPot::Model2String`
```R
	parms.eqn.x <- Model2String(var.eqn.x, parms = model.parms, supress.print = TRUE)
	parms.eqn.y <- Model2String(var.eqn.y, parms = model.parms, supress.print = TRUE)
```
For this simulation, we start our simulation at (1, 2), add Gaussian noise with a mean of 0 and a standard deviation of 0.05 every $\delta t = 0.025$, for a total time of $T = 1000$.

```R
model.state <- c(x = 1, y = 2)
model.sigma <- 0.05
model.time <- 1000
model.deltat <- 0.025

ts.ex1 <- TSTraj(y0 = model.state, time = model.time, deltat = model.deltat, x.rhs = parms.eqn.x, y.rhs = parms.eqn.y, sigma = model.sigma)
```
Or alternatively, one could also use TSTraj to combine equation strings and parameter values.
```R
ts.ex1 <- TSTraj(y0 = model.state, time = model.time, deltat = model.deltat, x.rhs = var.eqn.x, y.rhs = var.eqn.y, parms = model.parms, sigma = model.sigma)
```
### Visualizing the results
